/** Transparent animated source — inverted in UI via CSS; run `npm run icons:generate` */
export const BRAND_LOGO_SOURCE_URL =
  "https://pub-a25c26cd10394d818d79893e73296a9a.r2.dev/little_abby_trucking_transparent.gif";

/** Local copy of transparent logo (display with CSS invert on dark UI) */
export const BRAND_LOGO_URL = "/brand/logo.gif";

/** Inverted still for Clerk / contexts without CSS invert */
export const BRAND_LOGO_CLERK_URL = "/brand/logo-clerk.png";

export const BRAND_NAME = "Little Abby Trucking";

/** Square ABBY-mark favicons generated by scripts/generate-favicons.mjs */
export const BRAND_ICON_SIZES = [16, 32, 48, 64, 128, 180, 192, 512] as const;

export function brandIconUrl(size: (typeof BRAND_ICON_SIZES)[number]) {
  return `/icons/icon-${size}x${size}.png`;
}
